"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import Sidebar from "@/components/sidebar";
import Header from "@/components/header";
import Footer from "@/components/footer";
import React, { useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import AdminSidebar from "@/components/adminSidebar";

config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const pathname = usePathname();

  useEffect(() => {
    console.log("Current route:", pathname);
  }, [pathname]);

  const toggleSidebar = () => {
    setSidebarOpen(!sidebarOpen);
  };

  const isAdminRoute = pathname.startsWith("/admin");

  return isAdminRoute ? (
    <html lang="en">
      <body className={inter.className}>
        <div className="admin-layout">
          <AdminSidebar />
          <div className="admin-content">
            <main>{children}</main>
          </div>
        </div>
      </body>
    </html>
  ) : (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar sidebarOpen={sidebarOpen} toggleSidebar={toggleSidebar} />
        <div className="page-content">
          <Header toggleSidebar={toggleSidebar} />
          <main className="main-content">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}